"""Fix multiple users in a team

Revision ID: 84bccf75a25e
Revises: 699fcda29c74
Create Date: 2023-09-21 10:25:43.999230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84bccf75a25e'
down_revision = '699fcda29c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_team_id_users'), 'users', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_team_id_users'), type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
