"""Add language to exercise scores

Revision ID: b87cad02facf
Revises: 84bccf75a25e
Create Date: 2023-10-09 13:09:28.678036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87cad02facf'
down_revision = '84bccf75a25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_scores', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
